### ISSUE TITLE
Proposal: Use latex-utensils to parse TeX source

### ISSUE THREAD

**Issue by pddg** [nzt/textlint-plugin-latex2e#25]
VSCodeのLaTeXプラグインであるLaTeX Workshopの実装を見ているときに気付いたのですが，[latex-utensils](https://github.com/tamuratak/latex-utensils)というパッケージが内部で利用されているようです．

https://github.com/James-Yu/LaTeX-Workshop/blob/v8.5.0/src/components/parser/syntax.ts

このパッケージ自体がLaTeXパーサーの自前実装のためのものであるなら別ですが，textlintにおける利便性だけを考えるなら，既存の利用実績のあるパーサーを利用する方が良いのでは無いでしょうか．

既に検討されていたならすいません．

**Comment by fgborges** [comment]
提案ありがとうございます。まったく知らなかったですが、良さそうですね。
私自身パーサーのメンテナンスは大変だったので移動したいです。

**Comment by pddg** [comment]
良かったです！私自身でプロトタイプを提供できると良かったのですが，あまりこういったツールの実装のセオリーを知らない物で…
数日作業できない環境に身を置きますが，それ以降なら未実装のタスク等をIssueに書いて頂ければ多少は貢献できるかも知れません．よろしくお願いします🙏

**Comment by fgborges** [comment]
おそらく、https://github.com/fgborges/textlint-plugin-latex2e/blob/master/src/latex-to-ast/index.tsをつかって、ASTのリネームをすれば良いと思われます。早速ブランチを切って今週末とりかかります。

あと話がかわるのですが、textlint-plugin-latex2eを一緒に開発しませんか？コラボレーターとして招待したいです。自分自身のためにつくったのは良いものの、ドックフーディングが間にあってなかったので。

**Comment by pddg** [comment]
入れ違いになってしまいましたね．TypeScriptでの開発はこれが初めてなのですが，もし良ければよろしくお願いします！

**Comment by pddg** [comment]
しばらくlatex-utensilsを触っていたのですが，単にパース結果のマッピングをするだけでは十分でないように思います．latex-utensilsはコメントのツリーを以下のようにパースします．

```tex
\begin{document}
% comment
\section{Title}
abc
\end{document
```

```bash
$ npx luparse -c -l sample.tex
{
  "kind": "ast.root",
  "content": [
    # Some nodes
  ],
  "comment": [
    {
      "kind": "comment",
      "content": " comment",
      "location": {
        "start": {
          "offset": 17,
          "line": 2,
          "column": 1
        },
        "end": {
          "offset": 27,
          "line": 3,
          "column": 1
        }
      }
    }
  ]
}
```

<details><summary>出力全体</summary>

```json
{
  "kind": "ast.root",
  "content": [
    {
      "kind": "env",
      "name": "document",
      "args": [],
      "content": [
        {
          "kind": "command",
          "name": "section",
          "args": [
            {
              "kind": "arg.group",
              "content": [
                {
                  "kind": "text.string",
                  "content": "Title",
                  "location": {
                    "start": {
                      "offset": 36,
                      "line": 3,
                      "column": 10
                    },
                    "end": {
                      "offset": 41,
                      "line": 3,
                      "column": 15
                    }
                  }
                }
              ],
              "location": {
                "start": {
                  "offset": 35,
                  "line": 3,
                  "column": 9
                },
                "end": {
                  "offset": 42,
                  "line": 3,
                  "column": 16
                }
              }
            }
          ],
          "location": {
            "start": {
              "offset": 27,
              "line": 3,
              "column": 1
            },
            "end": {
              "offset": 42,
              "line": 3,
              "column": 16
            }
          }
        },
        {
          "kind": "text.string",
          "content": "abc",
          "location": {
            "start": {
              "offset": 43,
              "line": 4,
              "column": 1
            },
            "end": {
              "offset": 46,
              "line": 4,
              "column": 4
            }
          }
        },
        {
          "kind": "parbreak",
          "location": {
            "start": {
              "offset": 46,
              "line": 4,
              "column": 4
            },
            "end": {
              "offset": 47,
              "line": 5,
              "column": 1
            }
          }
        }
      ],
      "location": {
        "start": {
          "offset": 0,
          "line": 1,
          "column": 1
        },
        "end": {
          "offset": 61,
          "line": 5,
          "column": 15
        }
      }
    },
    {
      "kind": "parbreak",
      "location": {
        "start": {
          "offset": 61,
          "line": 5,
          "column": 15
        },
        "end": {
          "offset": 62,
          "line": 6,
          "column": 1
        }
      }
    }
  ],
  "comment": [
    {
      "kind": "comment",
      "content": " comment",
      "location": {
        "start": {
          "offset": 17,
          "line": 2,
          "column": 1
        },
        "end": {
          "offset": 27,
          "line": 3,
          "column": 1
        }
      }
    }
  ]
}
```

</details>

そのため，textlint-filter-rule-commentsのようなコメントを認識して動くフィルタなどを動作させることができません．locationのlineとcolumnを見て，適切な位置にコメントのノードを挿入する必要があるかも知れません…

**Comment by pddg** [comment]
GoのASTのパースにおけるコメントのマッピングを参考に上記の実装をやっていきたいと思っています．あまり時間が取れないので，3月以降になるかもしれません． https://github.com/golang/go/blob/4b4370066f/src/go/ast/commentmap.go#L127-L240

**Comment by nzt** [comment]
およそ、期待していたものが完成しつつあります。
しかしLaTeX-utensilsの仕様として空白文字をAST上で表現しないので、各ノードをつなげても、もとのソースコードに戻りません。つまり、現行では`parse("some text").toString() === "some text"` ですが、latex-utensilsでは、`parse("some text").toString() === "sometext"`となるため非互換のASTになります。そして、この非互換の変更は影響が大きく特にtextlint-util-text-to-sourceというパッケージと相性が悪いです。一つとしてtextlint-util-text-to-source側で虫食いのASTでも正しく動作するようにお願いすることが考えられますが、このパッケージはおよそすべてのルールで依存関係にあるため影響が大きいです。そのため、生成されたASTを補完する処理が必要になります。

しかし、この処理は結構ややこしそうなので時間がかかると思われます。
大体の方針は@pddgさんのいうようなコメントのマッピングと同様です。
コメントの他に空白文字もマッピングする感じで作る必要があるということですね。

関連：https://github.com/textlint/textlint-util-to-string/issues/13

**Comment by pddg** [comment]
なかなかままなりませんね……

コメントのマッピングですが私生活の多忙により停滞中です．申し訳ないです．

**Comment by nzt** [comment]
朝アイディアが思いつたので実装してみました。一応テストはすべて通ります。
v1.0.0-alpha.0としてリリースしたので、手元のドキュメント等でテストをお願い出来ますでしょうか？もし、問題がないようであれば今後はテストケースの充実にフォーカスしリリースに向け完成度を高める作業をしていきたいと思っています。その際は協力していただけると幸いです。

**Comment by pddg** [comment]
軽く動かしてみただけですが，どうも数式周りは軒並みダメなようです．もう少し探ってみて別Issueを建てたいですね．
単純な文章のみであれば少なくとも手元では問題は見られませんでした．テストの充実，少しずつでもお手伝い出来ればと思います．

**Comment by nzt** [comment]
latex-utensilsがリリースされ次第、今後予定されている作業を再開しましょう。

**Comment by nzt** [comment]
根拠はないのですが、latex-utensilsの新しい版はしばらくリリースされないような気がしています。したがってアップストリームの対応を待たずに私家版をnpmにアップロードして上流の変更を取り込みつつメンテナンスする形にしようとおもいます。

**Comment by nzt** [comment]
ひとまず、latex-utensilsのCanary版で変更が反映されているそうなのでそれを反映させました。これにて一旦issue25を閉じます。コメントの件は再び別のIssueを立てて作業していただけますでしょうか？
