### ISSUE TITLE
Object.fromEntries is not available in Node 10.x

### ISSUE THREAD

**Issue by pddg** [nzt/textlint-plugin-latex2e#32]
refs #25 

Node 12.xから利用可能な`Object.fromEntries`が含まれているため，Node 10.xでのCIが全てfailするようです．10.xは動作対象外としますか？

https://github.com/nzt/textlint-plugin-latex2e/blob/2bf4136966dfe0175a76da798cc452ddf046a4bf/src/latex-to-ast.ts#L27-L29

https://github.com/nzt/textlint-plugin-latex2e/runs/486945485

**Comment by nzt** [comment]
これは、ts-jestの設定の問題でtypescriptがes2019をターゲットにコンパイルしていることが原因だと思われれます。すこし、設定をいじれば治る問題だと思います。

**Comment by pddg** [comment]
MDNによるとfromEntriesはNode 12.xからのようなのですが，思い違いでしょうか（あんまり理解していないので見当違いのことを言っているかもしれません）

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries

**Comment by nzt** [comment]
おっしゃるとおりです。しかしTypeScriptにはいわゆるポリフィルを追加する機能があるので、コンパイル時に必要なポリフィル（ここではObject.fromEntriesに相当する機能を追加するパッチ）が同梱されるはずなのですが、JestやTypeScriptの設定で手抜きをしてたためポリフィルが適用されていないみたいです。https://developer.mozilla.org/ja/docs/Glossary/Polyfill

**Comment by pddg** [comment]
なるほど．理解しました．詳しくないのでその辺りはお任せします🙏

**Comment by nzt** [comment]
すみません。色々調べてみたらポリフィルじゃないっぽいです。お恥ずかしい…
とりあえず、なんとかしてみます。

**Comment by nzt** [comment]
なんとかできました！
